SDKVERSION = 7.0
ARCHS = armv7 arm64

include ../theos/makefiles/common.mk

BUNDLE_NAME = DotShortcut
DotShortcut_FILES = Switch.xm
DotShortcut_LIBRARIES = flipswitch
DotShortcut_FRAMEWORKS = UIKit
DotShortcut_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk
