include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = DotShortcutFS
DotShortcutFS_FILES = Switch.xm
DotShortcutFS_LIBRARIES = flipswitch
DotShortcutFS_FRAMEWORKS = UIKit
DotShortcutFS_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk
