SDKVERSION = 7.0
ARCHS = armv7 arm64

include ../theos/makefiles/common.mk

BUNDLE_NAME = AutoCapital
AutoCapital_FILES = Switch.xm
AutoCapital_LIBRARIES = flipswitch
AutoCapital_FRAMEWORKS = UIKit
AutoCapital_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk
