include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = AutoCapitalFS
AutoCapitalFS_FILES = Switch.xm
AutoCapitalFS_LIBRARIES = flipswitch
AutoCapitalFS_FRAMEWORKS = UIKit
AutoCapitalFS_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk
