include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = CapsLockFS
CapsLockFS_FILES = Switch.xm
CapsLockFS_LIBRARIES = flipswitch
CapsLockFS_FRAMEWORKS = UIKit
CapsLockFS_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk
