SDKVERSION = 7.0
ARCHS = armv7 arm64

include ../theos/makefiles/common.mk

BUNDLE_NAME = CapsLock
CapsLock_FILES = Switch.xm
CapsLock_LIBRARIES = flipswitch
CapsLock_FRAMEWORKS = UIKit
CapsLock_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk
