include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = AutoCorrectFS
AutoCorrectFS_FILES = Switch.xm
AutoCorrectFS_LIBRARIES = flipswitch
AutoCorrectFS_FRAMEWORKS = UIKit
AutoCorrectFS_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk
