SDKVERSION = 7.0
ARCHS = armv7 arm64

include ../theos/makefiles/common.mk

BUNDLE_NAME = AutoCorrect
AutoCorrect_FILES = Switch.xm
AutoCorrect_LIBRARIES = flipswitch
AutoCorrect_FRAMEWORKS = UIKit
AutoCorrect_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk
