SDKVERSION = 7.0
ARCHS = armv7 arm64

include ../theos/makefiles/common.mk

BUNDLE_NAME = CheckSpelling
CheckSpelling_FILES = Switch.xm
CheckSpelling_LIBRARIES = flipswitch
CheckSpelling_FRAMEWORKS = UIKit
CheckSpelling_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk
