include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = CheckSpellingFS
CheckSpellingFS_FILES = Switch.xm
CheckSpellingFS_LIBRARIES = flipswitch
CheckSpellingFS_FRAMEWORKS = UIKit
CheckSpellingFS_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk
